import Vue from 'vue'
import VueI18n from 'vue-i18n'

Vue.use(VueI18n)

export const i18n = new VueI18n ({
    local: 'en',
    locale: 'en',
    fallbackLocale: 'en',
    silentTranslationWarn: true,
    messages: {
        en: {
            csrfToken: document.getElementsByName('csrf-token')[0].value,
            root: {
                // Auth
                loginOrcreate: 'Login or Create an Account',
                new_customers: 'New Customers',
                by_creating: 'By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.',
                create_account: 'Create an account',
                registered_customer: 'Registered Customers',
                if_you_have: 'If you have an account with us, please log in.',
                name: 'Name',
                email_address: 'Email Address',
                password: 'Password',
                login: 'Login',
                submit: 'Submit',
                forgot_pwd: 'Forgot Your Password?',
                remembered_pwd: 'Remembered your password? Login',
            },
            auth: {
                name: 'Name',
                email_address: 'Email address',
                password: 'Password',
                remember_me: 'Remember me',
                login: 'Login',
                not_user: 'Not a user?',
                already_user: 'Already a user?',
                signup: 'Sign up',
                submit: 'Submit',
                rememberd_password: 'rememberd your password?',
                i_accpet: 'I Accpet our ',
                terms_condition: 'terms conditions',
                privacy_policy: 'privacy policy',
                new_password: 'New Password',
                con_new_password: 'Confirm New Password',
            },

            app: {
                profile: 'PROFILE',
                logout: 'LOG OUT',
                sidebar: 'Sidebar:',
                dark: 'Dark',
                light: 'Light',
                language: 'Language:',
                english: 'English',
                arabic: 'Arabic',
                search: 'SEARCH HERE...',
                welcome: 'WELCOME TO DASHBOARD',
                new_customers: 'NEW CUSTOMERS',
                new_orders: 'NEW ORDERS',
                new_visitors: 'NEW VISITORS',
                revenue: 'REVENUE',
                revenue_note: 'Revenue is the income that a business has from its normal business activities, usually from the sale of goods and services to customers.',
                dashboard: 'DASHBOARD',
                submit: 'SUBMIT',
                update: 'UPDATE',
                cancel: 'CANCEL',
                something_went_wrong: 'Something went wrong.',
                try_again: 'Try again',
                success_msg: 'Yo-ho-ho!, <br/>Request Successfully Completed.',
                error_msg: 'Opps, <br/>Something went wrong.',
                no_data: 'No data found.',

                all_data: 'ALL DATA',
                create_new: 'CREATE NEW',
                name_en: 'NAME (EN)',
                name_ar: 'NAME (AR)',
                image: 'IMAGE',
                actions: 'ACTIONS',
                active: 'ACTIVE',
                deactive: 'DEACTIVE',
                edit: 'EDIT',
                delete: 'DELETE',
                download: 'DOWNLOAD FILE',
            },

            nav: {
                main: 'MAIN',
                dashboard: 'DASHBOARD',
                categories: 'CATEGORIES',
                products: 'PRODUCTS',
                categories_upper: 'CATEGORIES',
                components: 'COMPONENTS',
                orders: 'ORDERS',
                reports: 'SALES',
                customers: 'CUSTOMERS',
                companies: 'COMPANIES',
                contracts: 'CONTRACTS',
                brands: 'BRANDS',
                models: 'MODELS',
                makes: 'MAKES',
                types: 'TYPES',
                messages: 'MESSAGES',
                settings: 'SETTINGS',
                authentication: 'AUTHENTICATION',
                employees: 'EMPLOYEES',
                permissions: 'PERMISSIONS',
                pages: 'PAGES',
                create_pages: 'CREATE PAGES',
                docs: 'DOCS',
                documentation: 'Documentation',
            },

            categories: {
                title: 'CATEGORIES',
                create: 'CREATE CATEGORY',
                update: 'UPDATE CATEGORY',
                type: 'TYPE',
                main_category: 'MAIN CATEGORY',
                image: 'IMAGE',
                name_en: 'NAME (EN)',
                name_ar: 'NAME (AR)',
                content_en: 'CONTENT (EN)',
                content_ar: 'CONTENT (AR)',
            },

            orders: {
                title: 'ORDERS',
                order_id: 'ORDER ID #',
                pro_count: 'PRODUCTS COUNT',
                total_price: 'TOTAL PRICE',
                date: ' CREATED AT',
                invoice: 'INVOICE',
                canceled_byUser: 'CANCELED BY USER',
                completed: 'COMPLETED',
                pending: 'PENDING',
                rejected: 'REJECTED',
                approve: 'APPROVED',
                image: 'IMAGES',
                desc: 'DESCRIPTION',
                unit_price: 'UNIT PRICE',
                qty: 'QTY',
                sub_total: 'SUB TOTAL',
                grand_total: 'GRAND TOTAL',
                tax: 'TAX',
                shipping_cost: 'SHIPPING COST',
                back: 'BACK',
                status: 'STATUS',

                year: 'YEAR:',
                make: 'MAKE:',
                model: 'MODEL:',
                submodel: 'SUBMODEL:',
                size: 'SIZE:',
                color: 'COLOR:',
                notes: 'NOTES:',
                invoice_date: 'INVOICE DATE',
                delivery_date: 'DELIVERY DATE',
                invoice_to: 'INVOICE TO:',
                payment: 'PAYMENT SUCCESS',
                not_payment: 'NOT PAID',
                shipping: 'SHIPPING',
                not_shipping: 'NOT SHIPPING',
                print: 'PRINT',
            },

            products: {
                title: 'PRODUCTS',
                create: 'CREATE PRODUCT',
                update: 'UPDATE PRODUCT',
                image: 'IMAGE',
                name_en: 'NAME (EN)',
                name_ar: 'NAME (AR)',
                category: 'CATEGORY',
                price: 'PRICE',
                views: 'VIEWS',
                basic: 'PRODUCT BASICS',
                categories: 'CATEGORIES',
                subcategories: 'SUB CATEGORIES',
                pro_no: 'PRODUCT NO.',
                brand: 'BRAND',
                type: 'TYPE',
                tax: 'TAX',
                shipping_cost: 'SHIPPING COST',
                colors: 'COLORS',
                options: 'PRODUCT OPTIONS',
                year: 'YEAR',
                make: 'MAKE',
                model: 'MODEL',
                submodel: 'SUB MODEL',
                size: 'SIZE',
                price: 'PRICE',
                qty: 'QTY',
                remove: 'REMOVE',
                add_more: 'ADD MORE',
                galleries: 'UPLOAD IMAGES',
                pro_details_en: 'PRODUCT DETAILS (EN)',
                pro_details_ar: 'PRODUCT DETAILS (AR)',
                specifications_en: 'SPECIFICATIONS (EN)',
                specifications_ar: 'SPECIFICATIONS (AR)',
                features_en: 'FEATURES (EN)',
                features_ar: 'FEATURES (AR)',
                warranty_en: 'WARRANTY (EN)',
                warranty_ar: 'WARRANTY (AR)',
                installation_en: 'INSTALLATION (EN)',
                installation_ar: 'INSTALLATION (AR)',
                faq_en: 'FAQ (EN)',
                faq_ar: 'FAQ (AR)',
                link_youtube: 'LINK YOUTUBE VIDEOS',
                upload_benefits: 'UPLOAD BENEFITS FILE',
                warranty_file: 'UPLOAD WARRANTY FILE',
                catalog_file: 'UPLOAD CATALOG FILE',
                addition_file: 'UPLOAD ANY ADDITION FILE',
            },

            models: {
                title: 'PRODUCTS MODELS',
                type: 'TYPE',
                main_model: 'MAIN MODEL',
                parent: 'Parent',
                no_parent: 'MAIN MODEL',
                note: 'Deleting a model does not delete the products in that model. Instead, products that were only assigned to the deleted model are set to the default model Uncategorized. The default model cannot be deleted.',
            },

            makes: {
                title: 'PRODUCTS MAKES',
                note: 'Deleting a makes does not delete the products in that make. Instead, products that were only assigned to the deleted make are set to the default make Uncategorized. The default make cannot be deleted.',
            },

            brands: {
                title: 'PRODUCTS BRANDS',
                note: 'Deleting a brand does not delete the products in that brand. Instead, products that were only assigned to the deleted brand are set to the default brand Uncategorized. The default brand cannot be deleted.',
            },

            types: {
                title: 'PRODUCTS TYPES',
                note: 'Deleting a type does not delete the products in that type. Instead, products that were only assigned to the deleted type are set to the default type Uncategorized. The default type cannot be deleted.',
            },
            messages: {
                title: 'MESSAGES',
                show: 'SHOW',
                name: 'NAME',
                email: 'EMAIL',
                date: 'DATE',
                mobile: 'MOBILE',
                msg: 'MESSAGE',
            },
            settings: {
                title: 'SETTINGS',
                logo: 'LOGO',
                title_en: 'TITLE (EN)',
                title_ar: 'TITLE (AR)',
                mobile: 'MOBILE',
                email: 'EMAIL',
                author_en: 'META AUTHOR (EN)',
                author_ar: 'META AUTHOR (AR)',
                keywords_en: 'META KEYWORDS (EN)',
                keywords_ar: 'META KEYWORDS (AR)',
                desc_en: 'META DESCRIPTIONS (EN)',
                desc_ar: 'META DESCRIPTIONS (AR)',
                address_en: 'ADDRESS (EN)',
                address_ar: 'ADDRESS (AR)',
                instagram: 'INSTAGRAM',
                twitter:'TWITTER',
                facebook: 'FACEBOOK',
            },
            employees: {
                title: 'EMPLOYEES',
                create_emp: 'CREATE EMPLOYEE',
                update_emp: 'UPDATE EMPLOYEE',
                image: 'IMAGE',
                name: 'NAME',
                email: 'EMAIL',
                mobile: 'MOBILE',
                password: 'PASSWORD',
                permissions: 'PERMISSIONS',
                history: 'HISTORY',
            },
            permissions: {
                title: 'PERMISSIONS',
                select_pages: 'SELECT PAGES TO APPEAR TO THIS USER',
            },
            pages: {
                title: 'PAGES',
                name_en: 'PAGE NAME (EN)',
                name_ar: 'PAGE NAME (AR)',
                content_en: 'PAGE CONTENT (EN)',
                content_ar: 'PAGE CONTENT (AR)',
                created_at: 'CREATED AT',
                actions: 'ACTIONS',
                create_page: 'CREATE PAGE',
                update_page: 'UPDATE PAGE',
            },
            edit: {
                new_products: 'NEW PRODUCTS',
                new_views: 'NEW VIEWS',
                new_sales: 'NEW SALES',
                company_profile: 'COMPANY PROFILE',
                sales: 'SALES',
                all_sales: 'ALL SALES',
                from: 'FROM',
                to: 'TO',
                image: 'IMAGE',
                description: 'DESCRIPTIONS',
                unit_price: 'UNIT PRICE',
                qty: 'QYT',
                total_price: 'TOTAL PRICE',
                tax_ship_cost: 'TAX + SHIPPING COST',
                date: 'DATE',
                category: 'CATEGORY',
                subcategory: 'SUB CATEGORY',
                all_orders: 'ALL ORDERS',
                contracts: 'CONTRACTS',
                logo: 'LOGO',
                company_name_en: 'COMPANY NAME (EN)',
                company_name_ar: 'COMPANY NAME (AR)',
                company_address_en: 'COMPANY ADDRESS (EN)',
                company_address_ar: 'COMPANY ADDRESS (AR) ',
                register_date: 'REGISTER DATE',
                total_payment: 'TOTAL PAYMENT',
                company_name: ' COMPANY NAME',
                payment: 'PAYMENT',
                companies: 'COMPANIES',
                license_no: 'LICENSE NO',
                products: 'PRODUCTS',
                sold: 'SOLD',
                new_company: 'NEW COMPANY',
                edit_company: 'EDIT COMPANY',
                name: 'NAME',
                email: 'EMAIL ADDRESS',
                username: 'USERNAME',
                mobile: 'MOBILE',
                password: 'PASSWORD',
                upload_contract: 'UPLOAD CONTRACT FILE',
            },
        },









        /* arabic language */
        ar: {
            csrfToken: document.getElementsByName('csrf-token')[0].value,
            auth: {
                name: 'الأسم',
                email_address: 'البريد الإلكترونى',
                password: 'كلمة المرور',
                remember_me: 'تذكرنى',
                login: 'تسجيل الدخول',
                not_user: 'لست عضواُ؟',
                already_user: 'هل ليدك حساب?',
                signup: 'تسجيل حساب جديد',
                submit: 'تسجيل',
                rememberd_password: 'تذكرت كلمة المرور?',
                i_accpet: 'انا أوافق علي ',
                terms_condition: 'الشروط والأحكام',
                privacy_policy: 'سياسة الخصوصية',
                new_password: 'كلمة المرور الجديدة',
                con_new_password: 'تأكيد كلمة المرور الجديدة',
            },

            app: {
                profile: 'بروفيلك',
                logout: 'تسجيل الخروج',
                sidebar: 'الخدمات',
                dark: 'أسود',
                light: 'أبيض',
                language: 'اللغة',
                english: 'الإنجليزية',
                arabic: 'العربية',
                search: 'بحث',

                welcome: 'WELCOME TO DASHBOARD',
                new_customers: 'العملاء الجدد',
                new_orders: 'الطلبات الجديدة',
                new_visitors: 'الزوار الجدد',
                revenue: 'الإيرادات',
                revenue_note: 'الإيرادات هي الدخل الذي تحققه الشركة من أنشطتها التجارية المعتادة ، عادةً من بيع السلع والخدمات للعملاء.',
                dashboard: 'لوحة التحكم',
                submit: 'حفظ',
                update: 'تعديل',
                cancel: 'إلغاء',
                something_went_wrong: 'حدث خطأ من الخادم',
                try_again: 'من فضلك حاول مرة آخرى',
                success_msg: 'تم تنفيذ طلبك بنجاح',
                error_msg: 'لم يتم تنفيذ طلبك',
                no_data: 'لا يوجد بيانات',

                all_data: 'جميع البيانات',
                create_new: 'أضف جديد',
                name_en: ' (EN) الأسم',
                name_ar: 'الأسم (AR)',
                image: 'الصورة',
                actions: 'الإعدادات',
                active: 'تفعيل',
                deactive: 'إلغاء التفعيل',
                edit: 'تعديل',
                delete: 'حذف',
                download: 'تحميل الملف',
            },

            nav: {
                main: 'الرئيسية',
                dashboard: 'لوحة التحكم',
                categories: 'الأقسام',
                products: 'المنتجات',
                categories_upper: 'CATEGORIES',
                components: 'الخدمات',
                orders: 'الطلبات',
                reports: 'المبيعات',
                customers: 'العملاء',
                companies: 'الشركات',
                contracts: 'العقود',
                brands: 'برندات المنتجات',
                models: 'موديلات المنتجات',
                makes: 'صناعات المنتجات',
                types: 'أنواع المنتجات',
                messages: 'الرسائل',
                settings: 'الإعدادات',
                authentication: 'الصلاحيات',
                employees: 'الموظفيين',
                permissions: 'الصلاحيات',
                pages: 'الصفحات',
                create_pages: 'أضف صفحة جديدة',
                docs: 'DOCS',
                documentation: 'Documentation',
            },

            categories: {
                title: 'الأقسام',
                create: 'أضف قسم جديد',
                update: 'تعديل القسم',
                type: 'النوع',
                main_category: 'قسم رئيسي',
                image: 'الصورة',
                name_en: '(EN) الأسم',
                name_ar: 'الأسم (AR)',
                content_en: '(EN) المحتوى',
                content_ar: 'المحتوى (AR)',
            },

            orders: {
                title: 'الطلبات',
                order_id: 'رقم الطلب #',
                pro_count: 'عدد المنتجات',
                total_price: 'إجمالي التكلفة',
                date: ' التاريخ',
                invoice: 'الفاتورة',
                canceled_byUser: 'تم إلغاءه من العميل',
                completed: 'تم الإنتهاء',
                approve: 'تم الموافقة',
                pending: 'جاري التجهيز',
                rejected: 'تم الرفض',
                image: 'الصور',
                desc: 'تفاصيل الطلب',
                unit_price: 'سعر الوحدة',
                qty: 'الكمية',
                total_price: 'إجمالي التكلفة',
                sub_total: 'التكلفة',
                grand_total: 'الإجمالي النهائي',
                tax: 'الضريبة',
                shipping_cost: 'تكلفة الشحن',
                back: 'رجوع',
                status: 'الحالة',

                year: 'السنة:',
                make: 'الصناعة:',
                model: 'الموديل:',
                submodel: 'الموديل الفرعي:',
                size: 'المساحة:',
                color: 'اللون:',
                notes: 'ملاحظات:',
                invoice_date: 'تاريخ الفاتورة',
                delivery_date: 'تاريخ الإستلام',
                invoice_to: 'الفاتورة إلى :',
                payment: 'تم الدفع بنجاح',
                not_payment: 'لم يتم الدفع',
                shipping: 'تم شحنه',
                not_shipping: 'ليس قابل للشحن',
                print: 'طباعة',
            },

            products: {
                title: 'المنتجات',
                create: 'أضف جديد',
                update: 'تعديل المنتج',
                image: 'الصورة',
                name_en: '(EN) الأسم',
                name_ar: 'الأسم (AR)',
                category: 'القسم',
                price: 'السعر',
                views: 'عدد المشاهدات',
                basic: 'أساسيات المنتج',
                categories: 'القسم الرئيسي',
                subcategories: 'القسم الفرعي',
                pro_no: 'رقم المنتج',
                brand: 'البراند',
                type: 'النوع',
                tax: 'الضريبة',
                shipping_cost: 'تكلفة الشحن',
                colors: 'الألوان',
                options: 'تفاصيل المنتج',
                year: 'السنة',
                make: 'الصناعة',
                model: 'الموديل الرئيسي',
                submodel: 'الموديل الفرعي',
                size: 'المقاس او الحجم',
                price: 'السعر',
                qty: 'الكمية',
                remove: 'حذف',
                add_more: 'أضف المزيد',
                galleries: 'أرفع صور آخرى',
                pro_details_en: '(EN) تفاصيل المنتج',
                pro_details_ar: 'تفاصيل المنتج (AR)',
                specifications_en: '(EN) المواصفات',
                specifications_ar: 'المواصفات (AR)',
                features_en: '(EN) المميزات',
                features_ar: 'المميزات (AR)',
                warranty_en: '(EN) الضمان',
                warranty_ar: 'الضمان (AR)',
                installation_en: '(EN) التركيب',
                installation_ar: 'التركيب (AR)',
                faq_en: '(EN) التعليمات',
                faq_ar: 'التعليمات (AR)',
                link_youtube: 'رابط الفيديو علي اليوتيوب',
                upload_benefits: ' ملف الفوائد',
                warranty_file: 'ملف الضمان',
                catalog_file: 'ملفا الكتالوج',
                addition_file: 'إي ملف آخر',
            },

            models: {
                title: 'موديلات المنتجات',
                type: 'النوع',
                main_model: 'موديل رئيسي',
                parent: 'نوع المديل',
                no_parent: 'موديل رئيسي',
                note: 'حذف الموديل لا يعني حذف المنتج المرتبط بيه, بل سوف يتم تحويله علي القسم الإفتراضي وهو غير مصنف إلي حين تعديله مرة آخرى',
            },

            makes: {
                title: 'صفناعات المنتجات',
                note: 'حذف الصناعة لا يعني حذف المنتج المرتبط بيه, بل سوف يتم تحويله علي القسم الإفتراضي وهو غير مصنف إلي حين تعديله مرة آخرى',
            },

            brands: {
                title: 'برندات المنتجات',
                note: 'حذف البراند لا يعني حذف المنتج المرتبط بيه, بل سوف يتم تحويله علي القسم الإفتراضي وهو غير مصنف إلي حين تعديله مرة آخرى',
            },

            types: {
                title: 'أنواع المنتجات',
                note: 'حذف النوع لا يعني حذف المنتج المرتبط بيه, بل سوف يتم تحويله علي القسم الإفتراضي وهو غير مصنف إلي حين تعديله مرة آخرى',
            },
            messages: {
                title: 'الرسائل',
                show: 'فتح',
                name: 'الأسم',
                email: 'البريد الإلكترونى',
                date: 'التاريخ',
                mobile: 'رفم الهاتق',
                msg: 'الرسالة',
            },

            settings: {
                title: 'الإعدادات',
                logo: 'اللوجو',
                title_en: '(EN) العنوان',
                title_ar: 'العنوان (AR)',
                mobile: 'رفم الهاتف',
                email: 'البريد الإلكترونى',
                author_en: '(EN) تاج المؤلف',
                author_ar: 'تاج المؤلف (AR)',
                keywords_en: '(EN) تاج كلمات البحث',
                keywords_ar: 'تاج كلمات البحث (AR)',
                desc_en: '(EN) تاج الوصف',
                desc_ar: 'تاج الوصف (AR)',
                address_en: '(EN) العنوان',
                address_ar: 'العنوان (AR)',
                instagram: 'INSTAGRAM',
                twitter:'TWITTER',
                facebook: 'FACEBOOK',
            },
            employees: {
                title: 'الموظفيين',
                create_emp: 'أضف موظف',
                update_emp: 'تعديل موظف',
                image: 'الصورة',
                name: 'الأسم',
                email: 'البريد الإلكترونى',
                mobile: 'رقم الهاتف',
                password: 'كلمة المرور',
                permissions: 'الصلاحيات',
                history: 'HISTORY',
            },
            permissions: {
                title: 'الصلاحيات',
                select_pages: 'أختر الصفحات المسموحة للمستخدم',
            },
            pages: {
                title: 'الصفحات',
                name_en: ' (EN) أسم الصفحة',
                name_ar: ' أسم الصفحة (AR) ',
                content_en: ' (EN) محتوي الصفحة',
                content_ar: ' محتوي الصفحة (AR) ',
                created_at: 'التاريخ',
                actions: 'الإعدادات',
                create_page: 'أضف صفحة جديدة',
                update_page: 'تعديل الصفحة',
            },
            edit: {
                new_products: 'المنتجات الجديدة',
                new_views: 'الزوار الجدد',
                new_sales: 'المبيعات الجديدة',
                company_profile: 'شركتي',
                sales: 'المبيعات',
                all_sales: 'جميع المبيعات',
                from: 'من',
                to: 'إلى',
                image: 'الصور',
                description: 'الوصف',
                unit_price: 'سعر الوحدة',
                qty: 'الكمية',
                total_price: 'الإجمالي',
                tax_ship_cost: 'الضرائب + سعر الشحن',
                date: 'التاريخ',
                category: 'القسم الرئيسي ',
                subcategory: 'القسم الفرعي ',
                all_orders: 'جميع الطلبات',
                contracts: 'العقود',
                logo: 'اللوجو',
                company_name_en: '(EN) أسم الشركة',
                company_name_ar: 'أسم الشركة (AR) ',
                company_address_en: '(EN) عنوان الشركة',
                company_address_ar: 'عنوان الشركة (AR) ',
                register_date: 'تاريخ التسجيل',
                total_payment: 'إجمالي المدفوع',
                company_name: ' أسم الشركة',
                date: 'التاريخ',
                payment: 'المبلغ المدفوع',
                companies: 'الشركات',
                license_no: 'رقم الترخيص التجاري',
                products: 'المنتجات',
                sold: 'المباع',
                new_company: 'أضف شركة جديدة',
                edit_company: 'تعديل الشركة',
                name: 'الأسم',
                email: 'البريد الإلكترونى',
                username: 'أسم المستخدم',
                mobile: 'رقم الهاتف',
                password: 'كلمة المرور',
                upload_contract: 'رفع ملف العقد',
            },

        },
    }
})